[build-system]
requires = [
    'setuptools',
    'wheel',
    'scikit-build',
    'cmake',
    'ninja',
]
build-backend = 'setuptools.build_meta'

[tool.black]
include = '.*\.py(\.in)?$'
extend-exclude = 'extern/'
