[build-system]
requires = [
    'setuptools',
    'wheel',
    'scikit-build',
    'cmake',
]
build-backend = 'setuptools.build_meta'

[tool.black]
include = '.*\.py(\.in)?$'
extend-exclude = 'extern/'

[tool.cibuildwheel.linux]
before-all = "yum install -y ninja-build"
