name: cd

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  python_wheels:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows Python wheels'
            os: windows-latest
          - name: 'Linux Python wheels'
            os: ubuntu-latest
          - name: 'macOS Python wheels'
            os: macos-latest
    steps:
      - name: Check out libOpenCOR
        uses: actions/checkout@v3
      - name: Configure MSVC
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build Python wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS: auto64
          CIBW_BUILD: 'cp*'
          CIBW_ENVIRONMENT: CIBUILDWHEEL=ON
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=11.0
          CIBW_ENVIRONMENT_PASS_LINUX: CIBUILDWHEEL
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_SKIP: '*musllinux*'
      - name: Upload Python wheel artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ./wheelhouse/*.whl
      - name: Release Python wheels
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./wheelhouse/*.whl
