name: ci

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows static library'
            os: windows-2016
            build_shared_libs: OFF
            build_type: Release
          - name: 'Windows shared library'
            os: windows-2016
            build_shared_libs: ON
            build_type: Release
          - name: 'Linux static library'
            os: ubuntu-20.04
            build_shared_libs: OFF
            build_type: Release
          - name: 'Linux shared library'
            os: ubuntu-20.04
            build_shared_libs: ON
            build_type: Release
          - name: 'macOS static library'
            os: macos-11
            build_shared_libs: OFF
            build_type: Release
          - name: 'macOS shared library'
            os: macos-11
            build_shared_libs: ON
            build_type: Release
          - name: 'Unit testing'
            os: ubuntu-20.04
            build_type: Debug
            target: unit_testing
          - name: 'Python unit testing'
            os: ubuntu-20.04
            build_type: Debug
            target: python_unit_testing
          - name: 'Code formatting'
            os: macos-11
            build_type: Release
            target: code_formatting
          - name: 'Coverage using gcov'
            os: ubuntu-20.04
            build_type: Release
            target: coverage_gcov
          - name: 'Coverage using llvm-cov'
            os: macos-11
            build_type: Release
            target: coverage_llvm_cov
          - name: 'Memory checks'
            os: ubuntu-20.04
            build_type: Debug
            target: memory_checks
    env:
      BUILDCACHE_COMPRESS_FORMAT: ZSTD
      BUILDCACHE_DEBUG: -1
      BUILDCACHE_DIRECT_MODE: true
      BUILDCACHE_LOG_FILE: ""
    steps:
      - name: Check out libOpenCOR
        uses: actions/checkout@v2
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install buildcache
        uses: mikehardy/buildcache-action@v1
        with:
          cache_key: ${{ matrix.name }}
      - name: Configure MSVC
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build libOpenCOR
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }} -DBUILD_TYPE=${{ matrix.build_type }} ..
          ninja ${{ matrix.target }}
