name: ci

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows Release'
            os: windows-2016
            mode: Release
          - name: 'Windows Debug'
            os: windows-2016
            mode: Debug
          - name: 'Linux Release'
            os: ubuntu-20.04
            mode: Release
          - name: 'Linux Debug'
            os: ubuntu-20.04
            mode: Debug
          - name: 'macOS Release'
            os: macos-11
            mode: Release
          - name: 'macOS Debug'
            os: macos-11
            mode: Debug
    env:
      BUILDCACHE_COMPRESS_FORMAT: ZSTD
      BUILDCACHE_DIRECT_MODE: true
    steps:
      - name: Check out libOpenCOR
        uses: actions/checkout@v2
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install buildcache
        uses: mikehardy/buildcache-action@v1
      - name: Build libOpenCOR
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DBUILD_TYPE=${{ matrix.mode }} ..
          ninja
