name: ci

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows'
            os: windows-2016
          - name: 'Linux'
            os: ubuntu-20.04
          - name: 'macOS'
            os: macos-11
    steps:
      - name: Install dependencies
        uses: lukka/get-cmake@latest
      - name: Check out libOpenCOR
        uses: actions/checkout@v2
      - name: Build libOpenCOR
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
