name: ci

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows"
            os: windows-latest
          - name: "Linux"
            os: ubuntu-latest
          - name: "macOS"
            os: macos-latest
    steps:
      - name: Install dependencies
        uses: lukka/get-cmake@latest
      - name: Check out libOpenCOR
        uses: actions/checkout@v2
      - name: Build libOpenCOR
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
