name: ci

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows CI"
            os: windows-latest
          - name: "Ubuntu CI"
            os: ubuntu-latest
          - name: "macOS CI"
            os: macos-latest
    steps:
      - name: Environment
        run: |
          echo "Name: ${{ matrix.name }}"
          echo "OS:   ${{ matrix.os }}"
      - name: Install dependencies
        uses: lukka/get-cmake@latest
      - name: Check out libOpenCOR
        uses: actions/checkout@v2
      - name: Build libOpenCOR
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
