name: libCellML

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  libcellml:
    name: libCellML
    uses: ./.github/workflows/buildThirdPartyLibrary.yml
    with:
      third_party_library_name: LIBCELLML
