name: libxml2

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  libxml2:
    name: libxml2
    uses: ./.github/workflows/buildThirdPartyLibrary.yml
    with:
      third_party_library_name: LIBXML2
