name: Spell check

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  spell_check:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Check out libOpenCOR
        uses: actions/checkout@v4
      - name: Spell check
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          skip: ./extern
          exclude_file: .codespellexclude
