name: wheels

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  wheels:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows wheels'
            os: windows-2016
          - name: 'Linux wheels'
            os: ubuntu-20.04
          - name: 'macOS wheels'
            os: macos-11
    steps:
      - name: Check out libOpenCOR
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.2
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: auto64
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
