name: wheels

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  wheels:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows wheels'
            os: windows-latest
          - name: 'Linux wheels'
            os: ubuntu-latest
          - name: 'macOS wheels'
            os: macos-latest
    steps:
      - name: Check out libOpenCOR
        uses: actions/checkout@v3
      - name: Configure MSVC
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: auto64
          CIBW_ENVIRONMENT_MACOS: >
            _PYTHON_HOST_PLATFORM=macosx-11.0-x86_64
          MACOSX_DEPLOYMENT_TARGET: 11
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
